version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: projeto-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: projetoextensao
      MYSQL_ROOT_HOST: '%'
    ports:
      - "3307:3306"iij
    volumes:
      - mysql_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    command: --default-authentication-plugin=mysql_native_password --bind-address=0.0.0.0 --skip-name-resolve

volumes:
  mysql_data:
